project:
  type: website

website:
  title: Marvel Cinematic Tidyverse
  navbar:
    right:
      - icon: github
        href: https://github.com/vizdata-s23/project-01-marvel_cinematic_tidyverse
    left:
      - text: Project
        href: index.qmd
      - text: "Proposal"
        href: proposal.qmd
      - text: "Presentation"
        href: presentation.qmd
      - text: "About"
        href: about.qmd

format:
  html:
    theme: default
    toc: true

execute:
  freeze: auto
